// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJxZhGd0ggTqBW9TIZDLeK8U9ktcSMEQ',
    appId: '1:256488829540:web:8a4d55af0bdbc37d302571',
    messagingSenderId: '256488829540',
    projectId: 'petner-51d9c',
    authDomain: 'petner-51d9c.firebaseapp.com',
    storageBucket: 'petner-51d9c.appspot.com',
    measurementId: 'G-TL6ZMJNKKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP1PVUdgQ9LHwkbwl8M4nnywkW38dO3I8',
    appId: '1:256488829540:android:cefded46c856f128302571',
    messagingSenderId: '256488829540',
    projectId: 'petner-51d9c',
    storageBucket: 'petner-51d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcyyPEfAIik8fS5-hfJ7kN4Nun4e943bc',
    appId: '1:256488829540:ios:dacc8e0af21d4d1d302571',
    messagingSenderId: '256488829540',
    projectId: 'petner-51d9c',
    storageBucket: 'petner-51d9c.appspot.com',
    iosClientId: '256488829540-i837bmssn7k34slskka4h7bracsmms8n.apps.googleusercontent.com',
    iosBundleId: 'br.com.Petner.PetnerApplication',
  );
}
